### ISSUE TITLE
Linux Compatibility with Git

### ISSUE THREAD

**Issue by LeeRuns** [CHC-CSU/Team-CHC-CSU#2]
i have built the file system for open foam in ubuntu, 
*will the files i have used remain compatible for someone running the program in windows?
can someone find a good explination of this?*

**Comment by mlreid358** [comment]
In short, no. System libraries which are used in all applications will be in different locations on every machine, even if they are running the same operating system. These system archives are linked (referenced for use) at compile time. The linker (part of the compiler package) cannot be invoked without object files which are essentially machine level code (and hence platform specific). Even if through a fluke you had the ubuntu built file system run in a windows executable environment I wouldn't trust the integrity of the results. You might have some luck if you used an ubuntu emulator in windows, but even then it would probably still need to be recompiled.

**Comment by LeeRuns** [comment]
So if we are going to be runni ng open foam or su2 we will all need to be on the same os? 

I thought this would work if everyone ran the same naming and organization of the c++ files. In open foam I was thinking I would just put the "run"  folder in a repository and it should run across the systems.

**Comment by LeeRuns** [comment]
I think that we should try to find the best cross platform solution for long term maintenance of the analysis tools we build. 

I added a git page in the wiki. Give it a look. It outlines some of the features that the company would like to see. The 2 features that I don't see within git is the ability to build security around the repository without paying some kind of liscensing fees. Long term I'm sure any corporation would want the repository to be only accessible with the companies intranet (firewall) and password protected within that.

**Comment by mlreid358** [comment]
Ah. When you said file structure, I wasn't sure what you meant. The raw and processed data (meshes matrices etc.) will all be portable, but the installation and some configuration settings of the programs will not be portable.

**Comment by LeeRuns** [comment]
I think you answer my question... Would be really easy for me to show you next time we get together.  Have u downloaded OpenFOAM, maybe if you downloaded it in Linux it would help.  I think we can have identical files across all platforms as long as we are only editing files within the "run" folder.  I think everything within that folder is a C++, python, or geometry file.   In reality the C++ files, are just scripts right?  So my thought was that anyone can edit that C++ file but then the command line codes we run to get the right directory set, that will change.  The commands that used should remain the same if we keep the folder the same, right?
