### ISSUE TITLE
how 2 change openfoam 2 running from git location

### ISSUE THREAD

**Issue by LeeRuns** [CHC-CSU/Team-CHC-CSU#28]
when i 1st installed openfoam it made a director in my home folder.  That contains the run file.  I have replicated it in the Git folder with a different name.  
_can i run it from windows?_
_does it matter that I renamed it_?
_is there a way that we could validate this as a completely working file so that we can branch off of it for running other cases?_

**Comment by LeeRuns** [comment]
think we will need to set it in our run directory as being in the git location....Let me know what we should do with this.

**Comment by LeeRuns** [comment]
**!
[image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8097aa7d59001d11190f2bd79485d174f278fa060a527ba58123286b8b126e15.png)
**

**Comment by LeeRuns** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-df29007380a0a4c881bdb7d059fd0e28590596bbb7d0455f2a80c262fde98b08.png)

**Comment by mlreid358** [comment]
Do you want to try to run this off git or wait and see if the server admin
will let us install on a shared drive?

**Comment by LeeRuns** [comment]
Want it on git then when we get server permission will just pull the repo
to the Lcsu linux  server
Chemical & Biological engineer
CSU & Carestream

**Comment by LeeRuns** [comment]
If the company has problems with open foam down the rd and wants to modify it. Could we actually edit the configuration files?

Is there an ide for editing configuration files?

**Comment by mlreid358** [comment]
There will be no IDE which supports foam configuration file language so far as I know. Should someone highly proficient in CFD want to edit how openFoam operates, all the source code is available at the site and could be recompiled with edits.
